name = "qhao-landing"
main = "index.ts"
compatibility_date = "2025-07-22"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"

[observability]
enabled = true
